CBS-843: Add code change and unit test in lunrdriver
rackerlabs/lunrdriver pull request #39
Opened 2021-05-27 10:47 UTC by mona-nanda

2021-05-27 14:56 UTC, sudhakar-datta commented
Mona, you need remove two lines, 185 and 186 in lunrdriver/api.py. We do not need another get_all call there.

2021-05-27 17:22 UTC, sudhakar-datta approved these changes
Looks Good overall, but require some minor/optional changes

2021-05-27 21:13 UTC, sudhakar-datta requested changes

2021-05-27 21:13 UTC, sudhakar-datta commented on lunrdriver/lunr/api.py
> +class SnapshotQuotaExceedConflict(exception.Invalid):
I prefer to be just SnapshotQuotaExceed. Conflict denotes something already in progress.

code 429 may be better, or 400 with message that it exceeded the total limit. 413 is mostly for payload related issues. Might need to check with Dan or Tyler as well

2021-05-28 09:36 UTC, mona-nanda commented on lunrdriver/lunr/api.py
> +class SnapshotQuotaExceedConflict(exception.Invalid):
added status code 429 for the conflict SnapshotExceeded

2021-05-28 15:03 UTC, sudhakar-datta approved these changes
LGTM

2021-05-28 15:49 UTC, jtwatson46 approved these changes
LGTM

2021-05-28 15:49 UTC, merged